import { z } from "zod";

/**
 * Bootstrap config = the YAML/JSON file + ENV/CLI merge result that's read at startup.
 * Per plan §4.2. Runtime config (globals/subscriptions/targets) lives under `dataDir`
 * and is owned by ConfigStore — NOT mixed in here.
 */

const ServerSchema = z.object({
	host: z.string().min(1).default("0.0.0.0"),
	port: z.coerce.number().int().min(1).max(65535).default(8787),
});

const BasicAuthSchema = z.object({
	username: z.string().min(1),
	password: z.string().min(1),
});

const AuthSchema = z
	.object({
		basicAuth: BasicAuthSchema.optional(),
		/**
		 * Origin whitelist for WS upgrade requests. Empty/undefined disables the
		 * Origin gate (and the WS layer logs a warning at boot). Required for any
		 * deployment exposed beyond localhost — see plan §4.2 / Fix 4b.
		 */
		allowedOrigins: z.array(z.string().min(1)).optional(),
	})
	.optional();

/**
 * Optional preset push targets injected at first boot to save the user from doing it
 * manually in the dashboard. Stage 2.1 stores them as opaque records — full Zod typing
 * lives in `@bilibili-notify/internal/schema/targets`, but the loader stays decoupled
 * so that adding a new platform later doesn't force a config-schema bump here.
 */
const PresetPushTargetSchema = z
	.object({
		name: z.string().min(1),
		platform: z.string().min(1),
		scope: z.enum(["group", "private", "channel"]).optional(),
		config: z.record(z.string(), z.unknown()).default({}),
	})
	.passthrough();

const PresetSchema = z
	.object({
		pushTargets: z.array(PresetPushTargetSchema).default([]),
	})
	.optional();

export const BootstrapConfigSchema = z.object({
	server: ServerSchema.default({ host: "0.0.0.0", port: 8787 }),
	dataDir: z.string().min(1).default("./data"),
	/**
	 * Reserved for the future GCM-AEAD cookie encryption path described in plan §4.1.
	 * As of stage 2.4 the master key still lives at `<dataDir>/secrets/master.key`
	 * (auto-generated by `KeyManager`) and StorageManager does not consume an external
	 * key. Do not delete — the field stays in the schema so existing config files
	 * remain valid and the migration to GCM can read it without a config-shape bump.
	 */
	cookieEncryptionKey: z.string().min(1).optional(),
	/**
	 * Absolute path to a Chromium / Chrome binary. Required for
	 * /api/cards/preview (puppeteer-core does NOT bundle a browser). Without
	 * it, the cards route reports 503 and the dashboard renders a config hint.
	 */
	chromePath: z.string().min(1).optional(),
	/**
	 * Directory holding the built React dashboard (`web/dist`). When set, the
	 * Hono app mounts a static file server for non-`/api/*` paths and falls
	 * back to `index.html` for SPA routes. When unset, the server is API-only
	 * (dev mode uses `vite` separately on port 5173). Docker images set this
	 * to `/app/web-dist` via `BN_WEB_DIST`.
	 */
	webDistDir: z.string().min(1).optional(),
	auth: AuthSchema,
	logLevel: z.enum(["fatal", "error", "warn", "info", "debug", "trace", "silent"]).default("info"),
	preset: PresetSchema,
});

export type BootstrapConfig = z.infer<typeof BootstrapConfigSchema>;
export type PresetPushTarget = z.infer<typeof PresetPushTargetSchema>;
